### ISSUE TITLE
Demanding paths

### ISSUE THREAD

**Issue by yvecai** [tracestrack/tracestrack-maps#1]
On the topo map, it seems every highway = path elements are rendered uniformeously. Maybe you'd like to take tags like trail_visibility, sac_scale or informal=yes into account not to give users a false security feeling.

**Comment by quinncnl** [comment]
Hi @yvecai it's a good suggestion. I'll try to come up with some variants based on `trail_visibility` and `sac_scale`.

**Comment by yvecai** [comment]
Here is how a set the cursor at Opensnowmap if it helps : https://github.com/OpenSnowMap-org/mapnik-opensnowmap.org/blob/master/k_snow_map/project.yml#L451
Of course my choices are debatable.

**Comment by quinncnl** [comment]
Some ground work has been done: https://github.com/tracestrack/osmdb-for-vis/tree/main

<img width="702" alt="Screenshot 2024-03-18 at 22 05 34" src="https://github.com/tracestrack/tracestrack-maps/assets/359745/c8446be8-732d-431a-9f20-9de55f185d23">

With various tag combinations I can start to try different styles.

**Comment by quinncnl** [comment]
<img width="863" alt="Screenshot 2024-03-19 at 22 26 06" src="https://github.com/tracestrack/tracestrack-maps/assets/359745/0a5e06ed-c0aa-4013-a44f-6f96d9dd783f">
<img width="1016" alt="Screenshot 2024-03-19 at 22 29 39" src="https://github.com/tracestrack/tracestrack-maps/assets/359745/0ffd5fff-b95b-4254-afe4-6a4e33ecc872">
<img width="1067" alt="Screenshot 2024-03-19 at 22 31 58" src="https://github.com/tracestrack/tracestrack-maps/assets/359745/80a82d20-2092-4f5e-a582-9665fcc4969d">

**Comment by yvecai** [comment]
I won't discuss the cartography, but this is cool to see the issue tackled with.

**Comment by osmuser63783** [comment]
Fantastic, I can see this on https://tracesmap.com in the street layer, are there any plans to enable this on the topo layer as well?

Also, would you consider enabling this for `highway=footway` and `steps`? There are areas of the world where many hiking paths are mapped as `footway` ([example](https://overpass-ultra.us/#run&m=10.42/54.5145/-3.1156&q=LQhQGcBcE8BsFMBcACAFpSAHciD0uo55wA6SAJwEMBLWKSk8VXAe03gDsBbSzSW4sBbguJAFbgWHUCGChcAKlAAVVNXDJ1ySh2TwAHpS6YEyAPIA3eOUyVwGgI4BXa9BIry0TZGQsnPgCMvTHJicGoOAHNkSFR4ZAAlJ10A-0gpbQCWKwBCUAVcUABtAKz9RABvCtKWfQBfOoBdAG5QAApQAHdKaCK1SNRu6ABeADMWFkghxqLwSgBjAH1wecoEFtAASla-H0j4Fi5m3eR5zkhrZqA)). There are about 18 ,000 `highway=footway` and 12,000 `highway=steps` with `sac_scale` tags.

**Comment by quinncnl** [comment]
@osmuser63783  It makes sense to support `footway` and `steps`. Just updated the style to support that. For topo map it should be enabled already. It takes some time to be rerendered.
