### ISSUE TITLE
Render leisure=bleachers

### ISSUE THREAD

**Issue by Hufkratzer** [tracestrack/tracestrack-maps#10]
Render [leisure=bleachers](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dbleachers)

OSM Carto doesn't render them; they have a discussion about it, but nobody made a PR yet.

**Comment by quinncnl** [comment]
Icon: https://www.flaticon.com/free-icon/bleachers_5029773?term=bleachers&page=1&position=1&origin=search&related_id=5029773

**Comment by quinncnl** [comment]
<img width="330" alt="Scherm­afbeelding 2023-11-19 om 21 31 27" src="https://github.com/tracestrack/tracestrack-maps/assets/359745/46f81f2e-15f3-4bf0-8a64-87a1fad9c26b">

Background will be like lighter park fill.

**Comment by quinncnl** [comment]
<img width="702" alt="Scherm­afbeelding 2023-11-19 om 21 41 59" src="https://github.com/tracestrack/tracestrack-maps/assets/359745/ba3768db-d83f-4ae9-8ab7-6b03b664d1f5">

https://www.openstreetmap.org/#map=19/49.62459/8.36702&layers=P
