### ISSUE TITLE
Paving stones surfaces

### ISSUE THREAD

**Issue by nclm** [tracestrack/tracestrack-maps#13]
Hi! I love this map style and has been using it on OSM as my default ever since I discovered it.

However, I think the style for areas paved with stones looks really out of style. It’s very dark and very visible. I also don’t remember it was like this a few weeks ago so it might be a recent change, though I might be wrong.

I’m talking of this styling:
<img width="104" alt="Screenshot 2023-12-07 at 10 12 03" src="https://github.com/tracestrack/tracestrack-maps/assets/923008/6cfbc5e8-8b39-49dc-a701-875e8c270edb">

For instances, a couple of screenshots of Copenhagen:
<img width="2099" alt="Screenshot 2023-12-07 at 10 13 23" src="https://github.com/tracestrack/tracestrack-maps/assets/923008/f5d9cae2-8fbc-4d65-86fd-ac5000a3d3f1">
<img width="1684" alt="Screenshot 2023-12-07 at 10 12 57" src="https://github.com/tracestrack/tracestrack-maps/assets/923008/8cfde444-6633-4a26-bfba-ff163f3a46eb">

The dark gray areas are standing out a lot. It’s so dark that it seems like a zone that cannot be accessed, my first thought when I encountered it was that those were construction sites.

I believe it should be made lighter, closer to the colours of streets or sidewalks. The patterning is nice and can be kept.

**Comment by quinncnl** [comment]
Hi! Thanks for your feedback. Some other people share the same view. I can try to make pedestrian areas lighter and similar to pedestrian roads. Will do some exploration on that.

**Comment by quinncnl** [comment]
<img width="826" alt="Scherm­afbeelding 2023-12-11 om 22 45 22" src="https://github.com/tracestrack/tracestrack-maps/assets/359745/0a6d7b42-f034-4583-8af5-62949c18c9c8">
<img width="952" alt="Scherm­afbeelding 2023-12-11 om 22 46 00" src="https://github.com/tracestrack/tracestrack-maps/assets/359745/aac1bbc9-af90-40fa-8d0e-6e06f04db742">

Updated opacity and it looks better!

**Comment by nclm** [comment]
Indeed thanks!

I wonder how it would look with a less contrasted outline stroke  (or none) as well? It kinda make it feel like a fence around it, while really you can walk easily though it. In reality most of the light gray between buildings and street lines (sidewalks, etc) is kinda the same as paved squares, places you can walk across. So having a dark gray line between the two is a little misleading?

**Comment by quinncnl** [comment]
Good idea! The gray border was from original carto style. Removed the border and it's clean and still recognizable. It's now updated and will be rerendered in a few days!

<img width="864" alt="Scherm­afbeelding 2023-12-12 om 21 59 20" src="https://github.com/tracestrack/tracestrack-maps/assets/359745/92ea1bf4-f15c-4cd9-9b15-710f70f3a3c1">
<img width="1026" alt="Scherm­afbeelding 2023-12-12 om 22 00 55" src="https://github.com/tracestrack/tracestrack-maps/assets/359745/059ca1a1-1ec6-4ea2-92fe-7061ab63e2ab">

**Comment by nclm** [comment]
This is great! Thanks, looking forward to the update :)
