### ISSUE TITLE
Issue with setting up this map by myself 

### ISSUE THREAD

**Issue by a14stoner** [tracestrack/tracestrack-maps#14]
Hello, 

i already set up both maps openstreetmap-carto and opentopomap. 
Now i saw this wonderful map but i cant get it done to set it up. 

It starts with the symbols. The symbols referenced in the styles are not existing in both openstreetmap carto and opentopomap. 

Do you somewhere have the symbols all together? Or is this repo not there to create the map my ourselfes? Just to reports changes or issues on the online map ?

Best regards
A14

**Comment by a14stoner** [comment]
Thanks for the info.
Symbols are totally enough. The DEM related part I alresdy have from opentopomap. 

Looking forward to it 👌

**Comment by a14stoner** [comment]
hey @quinncnl any timeframe you want to provide the needed data ?

**Comment by quinncnl** [comment]
hey @a14stoner I got busy lately with other stuff. There is quite some work to sync latest private code base to this open repository and fix the build. I will try to start working on it in March.

**Comment by quinncnl** [comment]
Hi @a14stoner I've updated the repo with symbols and tested with kosmtik. Please update the db connection to your environment before running it. The tif layers are all commented out.
