### ISSUE TITLE
Render amenity=bicycle_wash

### ISSUE THREAD

**Issue by mcliquid** [tracestrack/tracestrack-maps#16]
### Request
Today the proposal for `amenity=bicycle_wash` was accepted. In this context, I would also like to request the acceptance of this tag in the main OpenStreetMap style. The use of the tag will remain low, as there will never be a bike wash station on every street corner, but the icon is already prepared and linked here, so it would be a good thing to find it on the map.

### Links
OSM Wiki: https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_wash
Proposed Icon: https://wiki.openstreetmap.org/wiki/File:Bicycle_wash.svg
PR in iD tagging scheme: https://github.com/openstreetmap/id-tagging-schema/pull/1032

**Comment by quinncnl** [comment]
Hi! Looks good. Will add soon.

**Comment by quinncnl** [comment]
Updated. Render from z17 without `name` label.

An example can be found: https://www.openstreetmap.org/node/4404273499#map=19/44.65844/6.63867&layers=P
