### ISSUE TITLE
Add to Taginfo Projects

### ISSUE THREAD

**Issue by danieldegroot2** [tracestrack/tracestrack-maps#2]
Show the OpenStreetMap community what [data](https://wiki.openstreetmap.org/wiki/Tags) you are using. Add your project to the [list](https://taginfo.openstreetmap.org/projects) of [Taginfo Projects](https://github.com/taginfo/taginfo-projects).

**Comment by quinncnl** [comment]
Hi @danieldegroot2 thanks for the suggestion. I'll look into it and try to add the project to it.

**Comment by quinncnl** [comment]
Added: https://github.com/taginfo/taginfo-projects/pull/179
At the moment the taginfo only has landuse tags. Will complete it very soon. Closing the ticket.
