### ISSUE TITLE
Forest colour changes between z11 and z12

### ISSUE THREAD

**Issue by map-per** [tracestrack/tracestrack-maps#25]
| z11| z12|
|--------|--------|
| ![Screenshot (116)](https://github.com/tracestrack/tracestrack-maps/assets/79519062/356abbc9-8049-4ebe-85d2-1edbd3a2d32d) | ![Screenshot (115)](https://github.com/tracestrack/tracestrack-maps/assets/79519062/fc8ee975-f4cd-407b-8789-6e1a4ba2a7dd) | 

Why does the forest colour change between z11 and z12?
Using the darker colour on higher zooms as well would look nicer and more consistent in my opinion.

**Comment by quinncnl** [comment]
Hi thanks for bringing this up. From z9 to z11 raster landcover data (https://worldcover2021.esa.int/) is used. From z12 OSM data is used. The transition isn't tuned up very well indeed. Will check.

**Comment by map-per** [comment]
To me it looks like changing the colour value for forest [here](https://github.com/tracestrack/tracestrack-maps/blob/e986b0255ea831eb726787a0584ee97a25d67438/topo/style/landcover.mss#L5C11-L5C17) would do the trick.
Using a colour similar to the one in the raster landcover data would also make the colour choices more consistent on the higher zoom levels, with a lighter colour for grass and a darker one for forest. And it would look more similar to OSM Carto then.

**Comment by quinncnl** [comment]
Very much appreciate for opening this ticket. The forest color you pointed to somehow was different than it should be (the color in carto style). Since the impact is quite visible and big (all forest and wood at z>=11), ideally we should render all forests again.
Closing the ticket and will start to render forest by areas.

**Comment by map-per** [comment]
Thanks!
