### ISSUE TITLE
Better terrain mapping with natural=earth_bank

### ISSUE THREAD

**Issue by brocke** [tracestrack/tracestrack-maps#26]
For a better representation of the terrain and the topographical features of an area, you could also render the tag "natural=earth_bank".

It may not be used that often yet, but there are many situations where it could be used or where it could replace other tags that are actually used incorrectly (such as natural =cliff). As for the style, I would use the same as for man_made=embankment.

Thanks, Filip

**Comment by quinncnl** [comment]
Thanks for the suggestion! Looks like a good one to support. As you suggested, we can use the same svg as `embankment` but with a different color. An example usage: https://www.openstreetmap.org/way/1072450328#map=19/45.21902/5.62288&layers=P

**Comment by brocke** [comment]
Thank you for the positive response! I already know some places where I can use this tag and I'm looking forward to seeing it on the beautiful tracestrack map. And I hope that this will encourage other mappers to use the earth_bank tag as well.

**Comment by quinncnl** [comment]
Changes deployed. See an example here: https://www.openstreetmap.org/way/1266211713#map=18/49.12062/19.45527&layers=P

**Comment by brocke** [comment]
Very good! At what zoom level is it visible? I hope the same as with embankment.

And btw: I find it absolutely inspiring how quickly this feedback has found its way into implementation - respect!

**Comment by quinncnl** [comment]
The related code is like
```

#cliffs {
  [natural = 'cliff'][zoom >= 13] {
    line-pattern-file: url('symbols/cliff.svg');
    [zoom >= 15] {
      line-pattern-file: url('symbols/cliff2.svg');
    }
  }
  [natural = 'ridge'][zoom >= 14] {
    line-pattern-file: url('symbols/ridge-mid.svg');
    [zoom >= 15] {
      line-pattern-file: url('symbols/ridge2.svg');
    }
  }
  [natural = 'arete'][zoom >= 14] {
    line-pattern-file: url('symbols/arete-mid.svg');
    [zoom >= 15] {
      line-pattern-file: url('symbols/arete2.svg');
    }
  }
  [natural = 'earth_bank'][zoom >= 14] {
    line-pattern-file: url('symbols/earth_bank.svg');
  }
  [man_made = 'embankment'][zoom >= 15]::man_made {
    line-pattern-file: url('symbols/embankment.svg');
  }
```
So it should show even earlier than embankment. Let's see after the tiles are rerendered in a few days!
Thanks and any suggestions are welcome! (easier and less impactful ones are usually prioritized)

**Comment by brocke** [comment]
Hi again — it still can only be seen in zoom level 19. Shouldn't it be finished with tile rendering by now?

**Comment by quinncnl** [comment]
Hi @brocke , normally we render only changed areas with added/deleted nodes. If you made some changes it should appear in less then 10 days. If there is no changes it takes longer to be rerendered.
