### ISSUE TITLE
Render shrubbery a bit more explicit

### ISSUE THREAD

**Issue by pelderson** [tracestrack/tracestrack-maps#27]
Currently, natural=shrubbery renders just like grass. On the ground, there is quite some contrast between shrubbery (dense woody shrubs) and grass (with herb-like plants). 
Could shrubbery be rendered with a slight and darker cringle distributed over the green area with some random placement and orientation variation in it, suggesting dense leaves, to better resemble the visual impression? 
I am notoriously bad with images, but I know there are tools to create such backgrounds (random variation in placement is used for scrub, right?)

**Comment by quinncnl** [comment]
Thanks for the feedback. Indeed `shrubbery` is rendered as grass at the moment. It makes sense to render it differently. I can try to use the `scrub` pattern and the grass color. `flowerbed` is rendered similarly with `allotments` pattern and grass color (e.g. https://www.openstreetmap.org/way/1232022274#map=19/51.41782/5.40706&layers=P). It seems `scrub` is often misused as `shrubbery` (e.g. https://www.openstreetmap.org/way/1184275308)

**Comment by pelderson** [comment]
Thanks for the prompt reply! The scrub pattern on grass color would certainly be a vast improvement. Indeed, natural=scrub is often used instead of natural=shrubbery, because shrubbery does not render on OSM Carto. 
The major difference is that shrubbery tends to be a much smaller and well defined area with much denser vegetation of one or a very limited number of shrub types, usually with small leaves. 

If the pattern could be a bit denser and maybe with smaller "leaves", that would be great. If not, I'lll settle for scrub-on-grass!

**Comment by quinncnl** [comment]
I tried with denser scrub pattern but honestly it makes me uncomfortable and I'm sure it'll cause trypophobia to some people :) See

<img width="427" alt="Screenshot 2024-04-10 at 21 42 33" src="https://github.com/tracestrack/tracestrack-maps/assets/359745/5e106e8a-8718-41ce-9b7a-85b8af9f7fad">

I think scrub pattern is safer here.

<img width="516" alt="Screenshot 2024-04-10 at 21 45 40" src="https://github.com/tracestrack/tracestrack-maps/assets/359745/8076d6b6-90ae-45e3-964d-e8dc59207d89">

**Comment by quinncnl** [comment]
The style is updated and will deployed later today.

**Comment by pelderson** [comment]
? Is deployment to the Tracestrack layer on the osm.org site delayed? I see no effect, no matter how often I refresh!

**Comment by quinncnl** [comment]
It is. You can check some never-rendered places like https://www.openstreetmap.org/way/1154389537#map=19/55.55230/12.96627&layers=P.

Tiles are rerendered roughly every week so please see a few days later.
