### ISSUE TITLE
Missing texts

### ISSUE THREAD

**Issue by MartinPerry** [tracestrack/tracestrack-maps#29]
Hi, I have successfully rendered a basic map, but there are no texts. I have looked inside the mml file, but text "nodes" are missing. Is this a bug or intentional? I can copy them from the original OSM style, but due to some missing parts I would have to update SELECT queries probably.

**Comment by quinncnl** [comment]
Hi, the label layer is not open source yet. There is no timeline for that. Could be years but eventually it will be.
