### ISSUE TITLE
[CJK] Add support for Hong Kong SAR and Macau SAR locales

### ISSUE THREAD

**Issue by SCLu17** [tracestrack/tracestrack-maps#3]
Hong Kong (HK) and Macau (MO) use glyph sets that are distinct from both Mainland China’s and Taiwan’s. This is reflected in Noto Sans CJK via the ‘HK’ variant. Some common examples in-map include:

![rect26-1](https://github.com/tracestrack/tracestrack-maps/assets/85668984/6117314c-a1ad-4fd0-ab31-06528c68734a)
![rect26-2](https://github.com/tracestrack/tracestrack-maps/assets/85668984/57707aec-2825-4467-8032-7083412bbaa6)

This is incorrectly implemented in tracestrack, which uses the ‘SC’ variant for both regions:

![Screenshot from 2023-10-20 14-41-28](https://github.com/tracestrack/tracestrack-maps/assets/85668984/2e68aea9-7a44-4f4d-846c-071ecb7b5e2a)
![Screenshot from 2023-10-20 14-46-05](https://github.com/tracestrack/tracestrack-maps/assets/85668984/0900c896-e418-4276-9ad9-f56bc7913d26)

Since Japan and Taiwan already have relevant CJK localizations implemented, would it be possible to do the same for the two regions as well?

It should also be noted that for Noto/Source, there is no MO variant font file in the main release, only limited support in a [test release](https://github.com/adobe-fonts/variable-font-collection-test). See also https://ccjktype.fonts.adobe.com/2019/02/mscs.html. Since the MO glyph set is modified from the HK glyph set, and the HK glyph set is in turn modified from Taiwan’s TC set, I suggest using either the HK or TC variant for Macau in the meantime, and using the TC variant as a fallback font for both regions.

See also https://github.com/gravitystorm/openstreetmap-carto/issues/2208.
I refer also to the [HK government’s](https://www.ccli.gov.hk/en/hkscs/what_is_hkscs.html) and the [Macau government’s](https://www.safp.gov.mo/mscs/ivs/2020/default.htm) official documentations.

**Comment by quinncnl** [comment]
Hi @SCLu17, thanks for reporting. This is doable and will be fixed soon.

**Comment by quinncnl** [comment]
Fixed. See https://www.openstreetmap.org/#map=19/22.50421/114.27011&layers=P
Texts in Hong Kong and Macau are rendered with "Source Han Sans HC,思源黑體 香港".
It takes about 10 days to see the changes in updated maps.
