### ISSUE TITLE
Report of outdated cache at https://www.openstreetmap.org/#map=14/47.3832/10.3260&layers=P

### ISSUE THREAD

**Issue by SomeoneElseOSM** [tracestrack/tracestrack-maps#33]
Hello - Andy from OSM's Data Working Group here.

We've had a report of some outdated cache at https://www.openstreetmap.org/#map=14/47.3832/10.3260&layers=P due to the incident described at https://community.openstreetmap.org/t/the-osm-standard-tile-layer-looks-wrong-white-lines-abusive-comments-etc/111583 .

With the most recent example, the revert was only a few minutes after the most recent vandalism, but that was many days ago now - I'm surprised to see anything still appearing in cache. A number of third-party layers have been affected by this - see also https://github.com/cyclosm/cyclosm-cartocss-style/issues/675#issuecomment-2186806669 and https://en.osm.town/@KarlE@animexx.de/112670462177326427 .

If you'd like to contact the DWG directly please email data@openstreetmap.org with a subject line of "[Ticket#2024062510000432] tracetrack"

**Comment by quinncnl** [comment]
Hi! Thanks for the report. It's known to us and we've taken measures to rerender the affected areas. There might be a small amount of tiles missed. We'll try to invalidate all caches rendered on those days.

**Comment by quinncnl** [comment]
Closing as noted and done.
