### ISSUE TITLE
Rendering of pedestrian 

### ISSUE THREAD

**Issue by bveldkamp** [tracestrack/tracestrack-maps#35]
Rendering of pedestrian areas and ways is IMO inconsistent with the otherwise clean and modern look of Tracestrack.
Here's a screenshot I took [here](https://www.openstreetmap.org/#map=19/52.09150/5.11302&layers=PN) to illustrate some issues:

![Screenshot_20240817-100746~2](https://github.com/user-attachments/assets/7f1f93f7-945b-4ccd-83a2-2f34c3faf34e)

- Overlapping items result in kind of a moire pattern, eg where Boven Vredenburgpassage crosses Catharijne Esplanade, or near Man At Work
- Partial transparency over underlying areas looks a bit odd, eg the water area at the top, near Burger Federation 
- Jagged edges because areas have no outline

I realize this is all subjective, but would you consider modifying this symbology? 
I'm not a cartographer, but maybe a different kind of hatch, or a dotted symbol similar to orchards would be easier on the eyes ;-)

**Comment by quinncnl** [comment]
Hi! Thanks for the suggestion! Indeed ideally the line and area pattern shouldn't overlay on top of each other. I'll try to remove the pedestrian line pattern and try some variant decoration for it.

**Comment by quinncnl** [comment]
I did some test and found removing the pattern is cleaner and also easy to understand.

<img width="718" alt="Screenshot 2024-09-04 at 22 28 24" src="https://github.com/user-attachments/assets/511f7afe-e24a-450c-a79d-808b7c61494d">

Will update in the next rerender.
