### ISSUE TITLE
Rendering valley names

### ISSUE THREAD

**Issue by osmuser63783** [tracestrack/tracestrack-maps#38]
Are there any plans to include the names of valleys (`natural=valley`) in this style?

They're quite useful for finding your way around a map in a mountainous area, especially at low zoom levels (at higher zoom levels I suppose you'll want to render the names of the rivers, roads, paths instead which run along the valley bottom and would therefore conflict with the valley name).

OpenTopoMap shows them quite well I think but doesn't seem to be maintained or updated any more.

**Comment by quinncnl** [comment]
Thanks for the proposal. Looks good. Will support it soon.

**Comment by quinncnl** [comment]
<img width="833" alt="Screenshot 2024-11-03 at 23 09 15" src="https://github.com/user-attachments/assets/e88b1b42-1e56-4d51-ad06-3a36a20a9a56">

Started rendering ridge and valley from z10 in the same fonts.
