### ISSUE TITLE
Rendering of landuse=cemetery areas should be like a transparent overlay/underlay.

### ISSUE THREAD

**Issue by pelderson** [tracestrack/tracestrack-maps#40]
landuse=cemetery is defined as encompassing all the elements within the area. When no detail area are mapped within the cemetery, currently that works out acceptably on the map. However, when mapping details such as wood area, grass/grasland areas, garden sections, shrubbery beds, enclosed parking and buildings, only the sections with actual graves are rendered as landuse=cemetery. Whih is explicitly not the idea of landuse=cemetery!
Besides that, the dark green rendering does not fit the real world aspect and aerials of most cemeteries I know, except for the rows of trees and the thick hedges often found around the cemeteries.

Example of cemetery reduces to only the burial sections:
![image](https://github.com/user-attachments/assets/b7c4456d-c63d-495b-8c66-0578461b4916)

Aerial of the same site:
![image](https://github.com/user-attachments/assets/4defae1b-719d-4722-bf90-b5d59ccee6eb)

I would suggest (for now)
a. Rendering landuse=cemetery as a lighter hue of green, making sure the individual trees and hedges are much more prominent;
b. Rendering landuse=cemetery as a transparent overlay, making the tombstone logos appear over most of the detail landuse/natural/leisure areas. 

This way, mappers can map e.g. an thick wood outer border of a cemetery as a natural=wood and an inner garden or park section as leisure=garden or leisure=park, without trimming the cemetery to just the sections with graves. While still keeping the option to show the whole cemetery as one block in the lower zoom levels.

**Comment by quinncnl** [comment]
Thanks for the feedback. The micro-mapped cemetery is https://www.openstreetmap.org/way/1329185561.

Is `Essehof West` mapped correctly? https://www.openstreetmap.org/way/1329185561 It should cover the outer border of this part of the cemetery. The "vak X" tuin can just sit on top of it. The render engine draws small areas on top of bigger areas.

I checked other big cemeteries with many sections, like this https://www.openstreetmap.org/way/177382454#map=19/48.860519/2.391964&layers=P Maybe a better approach is to render `cemetery=sector` with border and ref. That way there is no need to put the vak number as a tuin.

The color part I agree. The color is too close to greeneries. 

Action point for now:
1) try to render `cemetery=sector` with ref and border
2) change cemetry color/add border

**Comment by pelderson** [comment]
> Is Essehof West mapped correctly? It should cover the outer border of this part of the cemetery. The "vak X" tuin can just sit on top of it. The render engine draws small areas on top of bigger areas.

Sorry, I tried to model this cemetery for better appearance with current rendering. I did not refer to this try-out directly because it bends the rules too much. The plan is to get back to regular modeling, hoping the rendering will be acceptable soon.

The whole cemetery is Essehof, it's a [polygon](https://www.openstreetmap.org/way/36872494) around the two parts Essehof West and Essehof Oost. The outline mostly  is in the water around the cemetary. 
The parts Essehof Oost and West are the wood areas outlining the whole cemetery, now tagged as landuse=cemetery with a tree_rows all around, which is more or less correct, but I want to retag that to natural=wood as soon as that does no longer make the entire border of the cemetery disappear. 

The idea to render landuse=cemetery lighter and with a border would achieve that. 

The sectors of this particular cemetery look much more like gardens than like dark green fields with tombstones. There are paths, trees, grass areas, shrubberies with decorative plants, flower beds, benches, hedges, artwork, water points, and, yes, graves. 
Still, if a suitable rendering for the sections is given which still shows the graves logos AND has a colour contrasting to the greenery (hedge, shrubbery, tree, flower_bed) on top of it, that would be much better, and I would delete the garden tags from the sectors.

**Comment by quinncnl** [comment]
<img width="761" alt="Screenshot 2024-11-04 at 21 22 38" src="https://github.com/user-attachments/assets/9b309a5d-913d-4510-883d-bb435b634ac7">

Using lighter color seems better.

**Comment by pelderson** [comment]
> Using lighter color seems better.

I agree. I like the "shine-through" tombstone pattern on the parking and buildings; this is what I had in mind for other naturals/landuses within the cemetery. Now, all smaller landuse/natural areas are cut out. 
I don't see the tree-rows I drew around the cemetery, nor the trees on the sections!

Note that the complete ring around the cemetery (within the cemetary terrain) should be tagged as natural=wood. If I retag that as would normally be done, almost the whole cemetery area would disappear! This would completely defeat the purpose of the landuse=cemetery.

If you want to use this cemetery to assess the rendering, I would like to undo my experimental mapping and tagging first! Is that OK with you?

**Comment by quinncnl** [comment]
Also I didn't add "border" to the cemetery. If you like border you can use `barrier=fence` or `barrier=wall`

**Comment by pelderson** [comment]
> Also I didn't add "border line" to the cemetery. If you like border you can use `barrier=fence` or `barrier=wall` on the cemetery area.

Sorry, I really can't do that - there is no fence and no wall; the cemetery is surrounded by water, grassland and wood, and the sectors are surrounded by hedges.

> Please use the standard way of tagging

I have returned Essehof West to the OSM-wiki standard way of tagging. The entire cemetery landuse is surrounded by a polygon tagged landuse=cemetery, name=Begraafplaats Essehof. 
(The east part still has my alternative mapping, including the sectors double tagged as gardens.)

**Comment by quinncnl** [comment]
<img width="780" alt="Screenshot 2024-11-17 at 01 05 01" src="https://github.com/user-attachments/assets/7206c9ad-e00b-4f41-97d6-18ea226c2126">

After database reimport `cemetery=sector`'s `name` and `ref` are now rendered (no border to start with). The tiles will be updated soon.

**Comment by pelderson** [comment]
I'm using the TT layer on osm.org. It doesn't seem to have updated for quite a while now. Can you tell me when the next update will be?

**Comment by quinncnl** [comment]
We were migrating the storage server a week ago, during which the update process was paused. Currently it's rendering the backlog as fast as possible. I expect NL regions will be rerendered in the next few days.

**Comment by pelderson** [comment]
The tiles are up to date now! The fill colour of cemetery is much better, the trees, shrubbery and hedges on it are now clearly visible, and the sector labels are clear. The tomb pattern is still a bit too dark in the sectors, I think. 

I see you closed the issue as completed, but this change does not affect the main issue: landuses that are within the cemetery polygon, are not displayed as part of the cemetery, but are cut out of the cemetery.  In the example Essehof, the naturals water, grass and wood all around reduce the cemetery to just the sections with graves, if these have no other landuse or natural tags. As most cemeteries in our country have trees and grass all around, they all look different (much smaller) on the map than in reality. 
So, this rendering does not match the definition of landuse=cemetery: the outline of the polygon and everything mapped inside it  is part of the cemetery. I think your idea of a border line around landuse=cemetery would be the easiest way to make it work.

**Comment by quinncnl** [comment]
I checked again. It looks like grass/woods covers the cemetery filling and symbols because they are smaller.

I see there are two cemetery:
small one: https://www.openstreetmap.org/way/45035085#map=18/51.959979/4.608920&layers=P
big one: https://www.openstreetmap.org/way/36872494#map=17/51.959533/4.608196&layers=P

I think if we add a border, the big one's border will be covered by water. Do you think it's better to use the water border as cemetery border? Then there is no overlapping and the border would be visible.

**Comment by pelderson** [comment]
> I think if we add a border, the big one's border will be covered by water. Do you think it's better to use the water border as cemetery border? Then there is no overlapping and the border would be visible.

In this case, where the water is actually on railway terrain, that would look good. I know other cemeteries where the water is definitely part of the cemetery, but I guess the cemetery border should then be drawn around the water.

**Comment by quinncnl** [comment]
With a border cemeteries look like this:

<img width="624" alt="Screenshot 2024-11-25 at 21 21 17" src="https://github.com/user-attachments/assets/570dfbef-a8eb-4acf-8a5b-4857d3c4a4dd">

<img width="688" alt="Screenshot 2024-11-25 at 21 21 39" src="https://github.com/user-attachments/assets/c66193fa-1ef4-41d1-bed8-85cb22029c00">

It's better I would say.

**Comment by quinncnl** [comment]
Deployed. Closing the ticket.

**Comment by pelderson** [comment]
I have waited to make sure all tiles are refreshed. There is still an issue: I see the border, but not always! This image shows two sides of the same cemetery. To the left: no border. The border is in the grass around the cemetery. (Earlier it was in the water but you said that that would be a problem).
To the right: the wood zone around the Essehof Oost is a separate landuse=cemetery. It shows up nicely, but this was an experimental tagging, it has to be restored to wood. 
What am I missing? 
![image](https://github.com/user-attachments/assets/f05f6862-8a2e-4cdd-aae7-9e399f8a54ca)

**Comment by quinncnl** [comment]
The left part has tombstone is rendered because of the big cemetery https://www.openstreetmap.org/way/36872494#map=17/51.959004/4.609666&layers=P
The right part is rendered with border because of another cemetery on top https://www.openstreetmap.org/way/45035085#map=18/51.960184/4.608791&layers=P

The border is applied on the cemetery polygon. It's possible that smaller woods or water cover the border the same way they cover the tombstone pattern. So if you like to put border around the pattern you have to draw border as a separate polygon.

**Comment by pelderson** [comment]
Right... But now we're back at square one: the issue is still that landuse=cemetery gets "eaten away" by naturals (landcovers), while it is defined in OSM as a polygon with all cemetery parts in it, including other landuses/naturals/amenities etc. Also, another landcover/natural such as grass or wood can be part inside the cemetery, part outside. The display does not show this when I use the correct mapping and tagging. 

> if you like to put border around the pattern you have to draw border as a separate polygon.

I have messed around with tagging for testing; the eastern half of thiscemetery shows that but it is not correct tagging; it is tagging for the renderer and has to be reversed after the test.
What exactly is the rendering rule about polygons covering each other? You say smaller woods or water, is that about surface area? Does that mean that if I enlarge the grass area enough, or cut up the cemetery area, then the cemetery border will show up?

**Comment by quinncnl** [comment]
I think what you want is to put border on top of everything (grass woods, water etc.) That can also be good. It will be like protected area border or country border. I will try it later today.

**Comment by quinncnl** [comment]
<img width="380" alt="Screenshot 2024-12-14 at 14 54 37" src="https://github.com/user-attachments/assets/cdb737d6-ca4b-485a-9c70-15f197003864" />

Hi @pelderson I've updated the label layers. Please use the standard mapping for the cemetery you mentioned. Let's see how it works out
