### ISSUE TITLE
Add render for roller_coaster=track

### ISSUE THREAD

**Issue by Nekzuris** [tracestrack/tracestrack-maps#44]
[roller_coaster=track](https://wiki.openstreetmap.org/wiki/Tag:roller_coaster=track) will soon have over 10k uses.

![image](https://github.com/user-attachments/assets/0c81f539-09d6-4aa9-b9d1-3cb7cd868b1d)

Way more than the already rendered [attraction=summer_toboggan](https://wiki.openstreetmap.org/wiki/Tag:attraction=summer_toboggan) with 1,500 uses.
For reference: [OSM Carto request](https://github.com/gravitystorm/openstreetmap-carto/issues/3596)

**Comment by quinncnl** [comment]
Looks good. Will support both of them soon.

**Comment by quinncnl** [comment]
Updated. Synced code with osm-carto.

<img width="964" alt="Screenshot 2024-11-25 at 21 04 21" src="https://github.com/user-attachments/assets/6f0d8b55-2229-4ea0-b532-f3c28db8a2a5">

See a new render: https://www.openstreetmap.org/#map=19/35.796711/-83.531292&layers=P
