### ISSUE TITLE
Enhance hillshade and elevation data

### ISSUE THREAD

**Issue by Nekzuris** [tracestrack/tracestrack-maps#48]
This is not urgent, but if you want to improve them in the future, here are some useful links:
[Collect and combine open elevation data](https://github.com/organicmaps/organicmaps/issues/4163)
[Sonny's LiDAR Digital Terrain Models of Europe](https://github.com/organicmaps/organicmaps/issues/7480)

**Comment by quinncnl** [comment]
Thanks. We are already using Sonny's Lidar for Europe, NASADEM and SRTM. We'll be looking to use more Lidar based DEM in US.

**Comment by quinncnl** [comment]
Closing for now. FYI we'll soon have a map tool to resolve elevation at a coordinates. That can be used to validate elevation accuracy.
