### ISSUE TITLE
Rendering natural=blockfield

### ISSUE THREAD

**Issue by StC-OSM** [tracestrack/tracestrack-maps#5]
![image](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Fontainebleau_place_cuvier.jpg/320px-Fontainebleau_place_cuvier.jpg)

The value `blockfield` for tag `natural` is relatively new (300 uses so far, see https://wiki.openstreetmap.org/wiki/Tag:natural%3Dblockfield) but it definitely fills a gap for boulder areas such as Fontainebleau forest in France (see https://commons.wikimedia.org/wiki/File:Fontainebleau_place_cuvier.jpg, https://www.openstreetmap.org/way/1216929655).

Replacing inappropriate tagging as `scree` or `bare_rock` should increase the numbers reasonably fast in the future.

It would definitely help the process of sorting out these tag values if `natural=blockfield` was rendered with a specific pattern in the Topo map.

**Comment by StC-OSM** [comment]
A peculiarity of this type of area is worth mentioning: it can coexist with a forest, where the trees grow between blocks or even sometimes on the blocks. This might require special care when rendering.

**Comment by 2dreamy** [comment]
> ![image](https://camo.githubusercontent.com/2fa247fa5c5ccef7dbe74d46892674957cf13d805ad37ea14f8306437e0b96d9/68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f7468756d622f632f63372f466f6e7461696e65626c6561755f706c6163655f6375766965722e6a70672f33323070782d466f6e7461696e65626c6561755f706c6163655f6375766965722e6a7067)
> 

Thank you.
Unfortunately, the picture above looks more like 'natural=stone' than 'block field'.

**Comment by StC-OSM** [comment]
It's actually difficult to find a proper photograph of the blockfield I gave as an example, half-hidden as it is under the trees. Here is an old picture from before the trees grew.
<img width="629" alt="Capture d’écran 2023-11-04 à 21 21 57" src="https://github.com/tracestrack/tracestrack-maps/assets/100076956/7ba75e75-415e-4cc8-b480-a7bbf9f5b5ba">

**Comment by quinncnl** [comment]
From wikipedia https://en.wikipedia.org/wiki/Blockfield there is also some description. They are indeed different from scree or bare_rock. Will add support for it.

**Comment by quinncnl** [comment]
<img width="612" alt="Scherm­afbeelding 2023-11-19 om 20 39 50" src="https://github.com/tracestrack/tracestrack-maps/assets/359745/e42e3deb-4951-4138-88b8-2b3d9da24adf">

<img width="881" alt="Scherm­afbeelding 2023-11-19 om 20 40 31" src="https://github.com/tracestrack/tracestrack-maps/assets/359745/5425d1e6-2ea1-4f2c-97ec-02316311cc5e">

Pattern generated from https://pattern.monster/concentric-circles-1/
