### ISSUE TITLE
Rendering boundary=forest_compartment and boundary=forest

### ISSUE THREAD

**Issue by StC-OSM** [tracestrack/tracestrack-maps#6]
In various countries, forests are subdivided into compartments and the compartment numbers are painted on trees (see https://p6.storage.canalblog.com/60/26/692115/131709412_o.jpg) and/or displayed on signage (see http://fontainebleau-foret.fr/SiteEncyclo/images/img_reperes/01.jpg).

The original goal of this is for forestry workers. But it has uses for hikers and other forest users, including:
 - locating yourself
 - analyzing temporary information that is displayed in the forest about hunting areas, ongoing works, regulations

That is, if these boundaries and reference numbers are displayed on maps. Which is the case for instance of this public map in France (see the light green numbers and thick lines):
<img width="949" alt="Capture d’écran 2023-11-04 à 10 52 27" src="https://github.com/tracestrack/tracestrack-maps/assets/100076956/c4cbb387-6b0b-4330-83c7-3019af70d9cc">

Rendering [boundary=forest_compartment](https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dforest_compartment) (and, optionally, [boundary=forest](https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dforest)) in the Topo map would definitely help for this. See https://overpass-turbo.eu/s/1CT9 for an example of such tags, in the same area as the example pictures above.

**Comment by Penegal** [comment]
Pretty good idea for orientation in forests with compartments!

**Comment by sylvain-m** [comment]
Very useful: I've been waiting for this for years! 👍

**Comment by quinncnl** [comment]
Should be a good addition. Will render the boundary with ref.

**Comment by quinncnl** [comment]
<img width="877" alt="Scherm­afbeelding 2023-11-09 om 21 08 21" src="https://github.com/tracestrack/tracestrack-maps/assets/359745/fe821853-01b0-4acc-82ed-3fdff9b27bc6">

Will be something like this. For low zoom I'll need to check a few more cases

**Comment by StC-OSM** [comment]
wow!

**Comment by StC-OSM** [comment]
Maybe a couple of attention points, though:
 - it looks like the red of paths combines with the green of boundaries to give something brownish. Maybe you'll prefer the paths to retain their color.
 - it may be hard to distinguish between forest boundaries and (here) the natural reserve boundary that crosses compartments 163 to 166.

**Comment by Penegal** [comment]
>     * it may be hard to distinguish between forest boundaries and (here) the natural reserve boundary that crosses compartments 163 to 166.

Maybe using a dashed outlines for compartments could do it?

**Comment by waterced** [comment]
> it looks like the red of paths combines with the green of boundaries to give something brownish. Maybe you'll prefer the paths to retain their color.

I was also noticing this. Keeping uniform path color would help maintaining good readability :)

**Comment by Penegal** [comment]
> I was also noticing this. Keeping uniform path color would help maintaining good readability :)

It looks like a problem with rendering priorities: the roads are also under the green outline. I would say that all `highway=*` features should be rendered after/above compartments; these should be rendered above `natural/landuse` areas, but under linear features such as highways.

**Comment by quinncnl** [comment]
> It looks like a problem with rendering priorities: the roads are also under the green outline. I would say that all highway=* features should be rendered after/above compartments; these should be rendered above natural/landuse areas, but under linear features such as highways.

Currently boundary and texts are rendered in label layer and roads are rendered in background layer. I would prefer adding compartments in label layers as other boundaries, which are on top of roads. We can add some offset to the boundary to avoid covering the path between two boundaries. I'll give that some try.

**Comment by quinncnl** [comment]
<img width="785" alt="Scherm­afbeelding 2023-11-11 om 22 28 39" src="https://github.com/tracestrack/tracestrack-maps/assets/359745/1514bbe2-9280-4305-a088-94a5fafe6d66">
<img width="1022" alt="Scherm­afbeelding 2023-11-11 om 22 31 27" src="https://github.com/tracestrack/tracestrack-maps/assets/359745/51c71757-3098-4cd7-b509-8674f0cbe48a">
<img width="1022" alt="Scherm­afbeelding 2023-11-11 om 22 31 27" src="https://github.com/tracestrack/tracestrack-maps/assets/359745/0248e968-374b-483a-a022-6193b46c26c7">

Dashed boundary is too noisy I think. I added offset and only render compartments from z15 (ref appears from z16). Let's see some final render then see what can be improved.

**Comment by quinncnl** [comment]
There is a temporary limitation: only `relation` compartments are rendered and `way` are not. This is due to the lua transformation script (https://github.com/gravitystorm/openstreetmap-carto/blob/master/openstreetmap-carto.lua#L56) needs to be changed. A full database reload will be needed for this.

**Comment by quinncnl** [comment]
<img width="1042" alt="Scherm­afbeelding 2023-11-12 om 21 04 50" src="https://github.com/tracestrack/tracestrack-maps/assets/359745/612d56a3-5867-4b13-a44b-66098f694364">

@Penegal It's indeed better with `compartment` under roads. There is a minor issue with label overlapping (see "HSA 02"). I tend to keep it as is. I'll render this area for preview.

**Comment by quinncnl** [comment]
I've manually refreshed this part of map for preview: https://tracesmap.com/#15/48.4171/2.5138/topo If you have more suggestions please reply.

**Comment by StC-OSM** [comment]
I tended to like the green numbers more than the black ones.

As for boundaries, now it's the red paths that change how we see the green boundaries. The way visual perception works is sometimes frustrating :-) But overall, as soon as you zoom enough it works well!

**Comment by Penegal** [comment]
Agree with @StC-OSM: green labels would be better, I think, even if it's only to highlight the logical link between labels and green boundaries.

**Comment by quinncnl** [comment]
> As for boundaries, now it's the red paths that change how we see the green boundaries. The way visual perception works is sometimes frustrating :-) But overall, as soon as you zoom enough it works well!

Overlapping elements are hard to visualize in general. We have to make a choice and sacrifice something :)

> Edit: I've tried this with OsmAnd on my iPhone. I believe that the boundaries should appear in one or even two more zoom levels, because currently it is hard to see more than one compartment at a time.

I've made it appear from z14 and ref from z15. 

Green label doesn't blend very well. I prefer using slightly darker boundary color.

<img width="740" alt="Scherm­afbeelding 2023-11-18 om 22 35 38" src="https://github.com/tracestrack/tracestrack-maps/assets/359745/5f1a3737-4e65-4e70-bc1b-a8f9b4b4d4ce">

**Comment by quinncnl** [comment]
<img width="855" alt="Scherm­afbeelding 2023-11-18 om 22 43 46" src="https://github.com/tracestrack/tracestrack-maps/assets/359745/f114300d-05fd-4ab5-b13a-04240a98dff3">

For now it'll be like this. I'll close the ticket. The updated source code will be synced later.
