### ISSUE TITLE
Render peak names instead elevation at "low" zoom levels

### ISSUE THREAD

**Issue by pyrog** [tracestrack/tracestrack-maps#7]
Elevations aren't useful at low zoom levels (12-14) but names are 😉 
Check other rendering to see differences ([CyclOSM](https://www.openstreetmap.org/#map=12/45.9381/6.3010&layers=Y), [Cycle map,](https://www.openstreetmap.org/#map=12/45.9381/6.3010&layers=C) [OpenTopoMap](https://opentopomap.org/#map=12/45.9381/6.3010)…)

Exemple: [Pointe de Dran](https://www.openstreetmap.org/#map=12/45.9381/6.3010&layers=P)

<img src="https://github.com/tracestrack/tracestrack-maps/assets/2158081/cd517ba9-057c-494c-8347-77096ced14e4" width=33%> <img src="https://github.com/tracestrack/tracestrack-maps/assets/2158081/a8615afb-7849-4c9f-9e41-7e2f130e8a23" width=33%>

**Comment by quinncnl** [comment]
Yes there is another discussion here: https://github.com/tracestrack/tracesmap.com/issues/3
This requires some investigation but will be done soon.

**Comment by quinncnl** [comment]
Some investigation gives following results:
1) peaks without name will show from z16
2) peaks with names will show from z13
3) peaks with ranking > 5 will show from z12
4) peaks with ranking > 20 will show from z10

Ranking currently use a simple algorithm: number of tags + `prominence/100` (prominence defaults to 100)

**Comment by quinncnl** [comment]
<img width="758" alt="Scherm­afbeelding 2023-11-25 om 12 50 24" src="https://github.com/tracestrack/tracestrack-maps/assets/359745/89fd9b62-570c-4219-9f4d-73f0d4938172">
<img width="581" alt="Scherm­afbeelding 2023-11-25 om 12 46 17" src="https://github.com/tracestrack/tracestrack-maps/assets/359745/9ad19433-4abf-4af9-9650-a824d19a78ee">

**Comment by quinncnl** [comment]
TODO: Same rule should also apply to volcano like https://www.openstreetmap.org/node/714354378#map=13/35.3590/138.7439&layers=P
