### ISSUE TITLE
Rendering of aerial ways 

### ISSUE THREAD

**Issue by pyrog** [tracestrack/tracestrack-maps#8]
Depending of the zoom level, the rendering of [aerialways](https://wiki.openstreetmap.org/wiki/Key:aerialway) is strange : 
Dots are too close or too far apart.

Could you render pylons a "high" zoom levels, and simply draw a line for the way itself (plus the stations) ?

Example: [Logère](https://www.openstreetmap.org/#map=19/45.78693/6.52145&layers=P)

<img src="https://github.com/tracestrack/tracestrack-maps/assets/2158081/1cb0d83b-83f7-4346-b67c-6bec457c8883" width=33%> <img src="https://github.com/tracestrack/tracestrack-maps/assets/2158081/e7289d5f-5b19-4c02-999f-2adb5f5e75bd" width=33%>

**Comment by quinncnl** [comment]
There was some misalignment before. Synced with osm-carto again.

<img width="1000" alt="Scherm­afbeelding 2023-11-18 om 23 41 53" src="https://github.com/tracestrack/tracestrack-maps/assets/359745/a0a30a54-aa6e-4560-992a-fc06a8a92f2b">

**Comment by quinncnl** [comment]
<img width="710" alt="Scherm­afbeelding 2023-11-18 om 23 53 45" src="https://github.com/tracestrack/tracestrack-maps/assets/359745/40da9bcf-f32d-4b94-8a28-a2c8643fcfa3">

Add some more spaces between dots at higher zoom.
