### ISSUE TITLE
Rendering of guideposts

### ISSUE THREAD

**Issue by pyrog** [tracestrack/tracestrack-maps#9]
`ref` aren't rendered, only `name` and `ele`.
According to zoom levels and tags, `ref — name`, `name` or `ref` could be rendered (± `ele` below) ?

Examples:
- [Mont Lachat, 1591 m](https://www.openstreetmap.org/node/5051050059#map=19/45.78700/6.52132&layers=P)
- [115](https://www.openstreetmap.org/node/4420524102#map=19/48.66847/2.05298&layers=P)
- [V63 — Bourget-du-Lac, 237 m](https://www.openstreetmap.org/node/4741371653)

**Comment by quinncnl** [comment]
It's an easy fix. Will update.

**Comment by quinncnl** [comment]
<img width="550" alt="Scherm­afbeelding 2023-11-18 om 23 27 24" src="https://github.com/tracestrack/tracestrack-maps/assets/359745/b2d13fc3-06e4-4b66-8caa-fe1d5c30a96f">

`ref` is rendered after name in parenthesis.
